### ISSUE TITLE
100% CPU usage on low end devices + Profiling details.

### ISSUE THREAD

**Issue by ixuz** [iotaledger/ict#12]
# System details:
* Model: Raspberry Pi Model B, Revision 2.0
* Kernel: Linux version 4.14.71+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1145 Fri Sep 21 15:06:38 BST 2018
* OS: Raspbian GNU/Linux 9.4 (stretch)
* CPU: BCM2835 (1 core 700 MHz)
* RAM: 512 MB

# General issue
All my Raspbery Pis (with System specs above) has a constant CPU usage of 100%.

# ICT version and Configuration
All my Icts operate on git commit: commit 33102b6df8784c9e0a4a6dd8890d38421bcd6b8d

```
name=ict
gui_enabled=false
gui_port=2187
port=14265
round_duration=60000
anti_spam_rel=5.0
anti_spam_abs=1000
tangle_capacity=1000
spam_enabled=false
min_forward_delay=0
neighbors=<host>:14265,<host>:14265,<host>:14265
host=0.0.0.0
max_forward_delay=200
```

# Profiling of CPU usage
I've taken the initiative to profile the Ict application while having three active neighbors.

## Ict transaction metrics:
```
20:56:57.117 INFO  [main/Main]   Starting new Ict 'ict' (version: 0.4-SNAPSHOT)
20:56:57.337 INFO  [main/Main]   Ict started on /0.0.0.0:9999.

20:57:57.331 INFO  [Sender/Neighbor]   ALL  |NEW  |REQ  |INV  |IGN     ADDRESS
20:57:57.333 INFO  [Sender/Neighbor]   135  |119  |0    |0    |0       <hostA>:12012
20:57:57.334 INFO  [Sender/Neighbor]   108  |2    |0    |0    |0       <hostB>:12013
20:57:57.334 INFO  [Sender/Neighbor]   101  |26   |0    |0    |0       <hostC>:12014

20:58:57.548 INFO  [Sender/Neighbor]   138  |0    |0    |0    |138     <hostA>:12012
20:58:57.548 INFO  [Sender/Neighbor]   132  |87   |0    |0    |0       <hostB>:12013
20:58:57.548 INFO  [Sender/Neighbor]   131  |60   |0    |0    |0       <hostC>:12014

20:59:57.850 INFO  [Sender/Neighbor]   152  |137  |0    |0    |0       <hostA>:12012
20:59:57.851 INFO  [Sender/Neighbor]   122  |2    |0    |0    |0       <hostB>:12013
20:59:57.851 INFO  [Sender/Neighbor]   93   |24   |0    |0    |0       <hostC>:12014
```
### Overview
![image](https://user-images.githubusercontent.com/7243912/51058666-c9e06380-15e9-11e9-9e45-176aac6b3157.png)
### Receiver deep look
![image](https://user-images.githubusercontent.com/7243912/51058679-d4026200-15e9-11e9-9bf8-d5e42f593408.png)
### Sender deep look
![image](https://user-images.githubusercontent.com/7243912/51058690-dfee2400-15e9-11e9-8984-6070534d249b.png)

## General hotspots profiling
![image](https://user-images.githubusercontent.com/7243912/51058703-eb414f80-15e9-11e9-9a85-ea8e14c9fe78.png)

# Final thoughts
More than 95 percent of the CPU usage is used for hashing and encoding/decoding of trytes to/from bytes. Optimization of these specific functions will yield good performance return and allow low-end devices like first generation Raspberry Pi's to participate in the Ict network.

**Comment by mikrohash** [comment]
https://github.com/iotaledger/ict/commit/85349f9e1f20d3136e681baf958d9b50fc691d38 should increase performance significantly but is incompatible with current Ict protocol (version 0.3).
