### ISSUE TITLE
Web GUI removes neighbors

### ISSUE THREAD

**Issue by Qaamien** [iotaledger/ict#14]
If you change anything on CONFIG and save changes, it removes all your neighbors

**Comment by gastrocole** [comment]
This also happens when you remove one neighbour using web gui, all neighbours are removed.

**Comment by lambtho12** [comment]
Note that if people used the all-in-one script to install ict, their config file is located in an other folder and ict is run using a systemd service with `java -jar ict-0.4.jar -c /path_to_config/ict.cfg` . Maybe the webGUI does not save the config in the right place or something.

**Comment by Qaamien** [comment]
Sure, but i didn't use that script.
