### ISSUE TITLE
Add possibility to rename/set alias for a neighbour

### ISSUE THREAD

**Issue by svenger87** [iotaledger/ict#15]
As a ICT maintainer with several hosts I want to rename a neighbor from hostname/IP or something more noticeable. Like a discord handle for example.

**Comment by lambtho12** [comment]
Yes it is definitely a good idea. But I guess it should be kept in the webGUI parameters, in order to avoid bloating the ict.cfg file with unnecessary stuff.

**Comment by svenger87** [comment]
> Yes it is definitely a good idea. But I guess it should be kept in the webGUI parameters, in order to avoid bloating the ict.cfg file with unnecessary stuff.

That's exactly what I meant :)

**Comment by ixuz** [comment]
I like this feature suggestion, to be able to put a label/note on each neighbor node.

**Comment by mikrohash** [comment]
fixed. add neighbor through format `personal note/host:port`
