### ISSUE TITLE
General: Usage of technical terms 

### ISSUE THREAD

**Issue by Citrullin** [iotaledger/ict#20]
Hey short question: Can we start using technical terms?

I am referring to the following:
"The Iota Controlled agenT is a light-weight IOTA node for the Internet-of-Things relying on swarm logic."

So what does this mean? Should ICT also run on Microcontroller? Or should it only run on SBCs? I would add this to the README, so that nobody has wrong expectations. :)

**Comment by mikrohash** [comment]
more technical documentation is now available [here](https://github.com/iotaledger/ict/blob/master/docs/ARCHITECTURE.md)

> An Ict node is deployed on some kind of server, usually a VPS or a raspberry PI.
