### ISSUE TITLE
IXI config not showing directly in Web GUI

### ISSUE THREAD

**Issue by lambtho12** [iotaledger/ict#27]
### Bug description
When a new IXI is added through the wbeGUI, the config tab for that IXI does not show directly. It will only show after a page refresh. 

### Ict version
Ict 0.5

### Hardware Spec
Raspberry Pi 3b+ , diepti

### Steps To Reproduce
1. Install any IXI through the web GUI

### Expected behaviour
Page should refresh automatically or config should appear directly.

### Actual behaviour
Config does not appear on its own and require user to manually refresh the page.

### Errors
N/A

**Comment by mikrohash** [comment]
@rihardsgravis
