### ISSUE TITLE
Impossible to switch between IXIs config directly in WebGUI

### ISSUE THREAD

**Issue by lambtho12** [iotaledger/ict#28]
### Bug description
When multiple IXI are installed, it is impossible to directly switch from one config to the other in webGUI. Only the title of the config box is updated, but not the fields

### Ict version
Ict 0.5

### Hardware Spec
Raspberry Pi 3b+ , diepti

### Steps To Reproduce
1. Install 2 different IXIs (tested with Chat and Report)
2. In webGUI, click on chat config, then report config

### Expected behaviour
Config fields should change accordingly

### Actual behaviour
Only title is updated, the fields stays the same. (e.g. if chat is opened first, then clicking on report will still show you the chat config fields and not the ones of report)

### Errors
N/A

**Comment by mikrohash** [comment]
@rihardsgravis
