### ISSUE TITLE
Password change in GUI leads to error for IctRestCaller

### ISSUE THREAD

**Issue by lambtho12** [iotaledger/ict#29]
### Bug description
When the password is changed in the GUI, a line is printed in the logs with 
`ERROR [Timer-2/IctRestCaller]   Failed to call ict-rest api, status code: 401. `
I am running Ict + chat + report. I guess the problem comes from the IXI still using the old one.

### Ict version
Ict 0.5

### Hardware Spec
Raspberry Pi 3b+ , diepti

### Steps To Reproduce
1. Change password in GUI

### Expected behaviour
No error, password should update in the IXI config as well. Or at least display a warning to ask user to change in IXI configs.

### Actual behaviour
Error is raised in log.

### Errors
`ERROR [Timer-2/IctRestCaller]   Failed to call ict-rest api, status code: 401. `

**Comment by mikrohash** [comment]
Looks like this is an issue of report.ixi not Ict.
