### ISSUE TITLE
Bug in neighbor address check

### ISSUE THREAD

**Issue by georgmittendorfer** [iotaledger/ict#3]
In certain cases it is possible that checking the neighbor address is not working. This will lead to log messages like:

`... WARN  [Receiver/Ict]  Received transaction from unknown address: /w.x.y.z` for a neighbor `some.address.com/w.x.y.z:14265` and the transaction will not get processed.

Reason for that probably is the code in `Receiver`:

```
private Neighbor determineNeighborWhoSent(DatagramPacket packet) {
        for (Neighbor nb : ict.getNeighbors())
            if (nb.getAddress().equals(packet.getSocketAddress()))
                return nb;
        // [...]
    }
```
The equals check does not work for all cases (dependent on dns resolving or port - didn't investigate in detail). I would bet on the port number as in the case above one of the neighbors was behind a firewall (NAT). This seems to be similar to the following IRI issue: https://github.com/iotaledger/iri/issues/961

**Comment by mikrohash** [comment]
Please report back whether 01666e459d7470db22733ec8c05d9f06709ac534 fixes it.

**Comment by georgmittendorfer** [comment]
Couldn't test as error did happen on another ict node (only saw the log message and checked the code after that). But the fix looks fine. If tests the address without the port it should work.

**Comment by georgmittendorfer** [comment]
I copied a test case over from IRI issue mentioned above. The `neighbor.sentPacketFromSameIP` method works as expected. Was to lazy to create a pull request, just copy and paste if you want to add it:

```
package org.iota.ict.network;

import org.junit.Test;

import java.net.DatagramPacket;
import java.net.InetSocketAddress;

import static org.junit.Assert.*;

public class NeighborTest {

    private final Neighbor neighbor = new Neighbor(new InetSocketAddress("localhost", 42));

    @Test
    public void sameIpWhenMatchesThenTrue() {
        assertTrue("expected match", neighbor.sentPacketFromSameIP(packetFrom("localhost", 42)));
        assertTrue("expected match", neighbor.sentPacketFromSameIP(packetFrom("localhost", 666)));
        assertTrue("expected match", neighbor.sentPacketFromSameIP(packetFrom("127.0.0.1", 42)));
        assertTrue("expected match", neighbor.sentPacketFromSameIP(packetFrom("127.0.0.1", 666)));
    }

    @Test
    public void differentIpWhenMatchesThenFalse() {
        assertFalse("expected no match", neighbor.sentPacketFromSameIP(packetFrom("google-public-dns-a.google.com", 42)));
        assertFalse("expected no match", neighbor.sentPacketFromSameIP(packetFrom("8.8.8.8", 42)));
    }

    private DatagramPacket packetFrom(String hostOrIp, int port) {
        return new DatagramPacket(new byte[] {}, 0, new InetSocketAddress(hostOrIp, port));
    }

}```

**Comment by mikrohash** [comment]
Thank you! 👍

**Comment by georgmittendorfer** [comment]
You are welcome! Did you see my comment on the double check in Receiver? I added it to a previous commit but can't find it anymore. I repeat it here:

```
 private Neighbor determineNeighborWhoSent(DatagramPacket packet) {
        for (Neighbor nb : ict.getNeighbors())
            if(nb.sentPacket(packet))
                return nb;
        for (Neighbor nb : ict.getNeighbors())
            if(nb.sentPacketFromSameIP(packet))
                return nb;
        Ict.LOGGER.warn("Received transaction from unknown address: " + packet.getAddress());
        return null;
    }
```

It seems to me that the first check in Receiver is redundant as the second check will get invoked if the first fails and this one will pass with a different port. Or am I missing something?

**Comment by mikrohash** [comment]
There are two checks in case you are connected to at least two Icts running on different ports of the same address. In that case, it's necessary to differentiate them by their port first to not confuse them with each other.

**Comment by georgmittendorfer** [comment]
OK, I understand, this will work, if only one of them is behind a firewall that does translate the port on NAT.
