### ISSUE TITLE
Neighbor History getting too large

### ISSUE THREAD

**Issue by mikrohash** [iotaledger/ict#31]

**Comment by a223y** [comment]
This is client only bug in JavaScript, right? So it requires to get Neighbor history to get in groups of minutes or 30sec intervals from node trough api(can't help with that, I'm not Java guy). I can offer you a javascript data structure for fixed size of element, I'm going to implement it, but soonest point of it being done is 36 hours from now, so if you can wait, I can do.

**Comment by mikrohash** [comment]
@a223y No it's actually a problem of the java backend rest API. Sending too large of a jason array to the GUI frontend.

**Comment by a223y** [comment]
You can actually only send update via websocket.

**Comment by a223y** [comment]
Actually there is even possibility to web-gui non freeze on server error.
