### ISSUE TITLE
Wrong color in Neighbor graph in webGUI

### ISSUE THREAD

**Issue by lambtho12** [iotaledger/ict#32]
@rihardsgravis 
When the mouse hovers on the graph of neighbor activity to display the actual numbers, the "grey" line (supposed to be new tx) turns red (which is for invalid tx). Therefore it does not match the legend displayed beneath the graph or next to mouse pointer.

**Comment by mikrohash** [comment]
Looks like all lines change colors except for the `all` line.

**Comment by mikrohash** [comment]
# no hover:
![nohover](https://user-images.githubusercontent.com/33261108/53693567-9bd5ff00-3da2-11e9-9fdf-679135f9a9ae.png)

# hover:
![hover](https://user-images.githubusercontent.com/33261108/53693566-9bd5ff00-3da2-11e9-9bc7-89007b9a1aa8.png)
