### ISSUE TITLE
Automatic installer error reporting

### ISSUE THREAD

**Issue by a223y** [iotaledger/ict#33]
```Installation of module iotaledger/chat.ixi failed: ./modules/chat-1.4.ixi```

What about some descriptive erros? 

In logs there is only "Downloading ./modules/chat.ixi-1.4.jar ..."

Naming of errors would be nice, e.g. "file permission error" would be really good and readable... Current state is not.

**Comment by lambtho12** [comment]
What do you called automatic installer ? The all-in-one script of https://github.com/phschaeff/ict-install ?
If yes, it is from the community (phschaeff) and has nothing to do with Ict directly.

**Comment by a223y** [comment]
I mean that thing on web gui.

**Comment by a223y** [comment]
You can't install component trough web gui, if it doesn't have write permissions, but the error is unspecific.

**Comment by mikrohash** [comment]
Usually there should be an explanation. Could you please provide the full error stack trace from your Ict console so I can investigate the issue?

**Comment by a223y** [comment]
You don't need error stack, error disappeared after I ```chown -r ict /var/lib/ict```. I didn't even checked the console, but it would for sure help somebody if this error was on GUI.

**Comment by a223y** [comment]
```Feb 26 11:05:40 iota-node iri[20948]:         at java.lang.Thread.run(Thread.java:748)
Feb 26 11:05:40 iota-node iri[20948]: Caused by: java.nio.file.AccessDeniedException: ./modules/chat.ixi-1.4.jar
Feb 26 11:05:40 iota-node iri[20948]:         at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
Feb 26 11:05:40 iota-node iri[20948]:         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
Feb 26 11:05:40 iota-node iri[20948]:         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
Feb 26 11:05:40 iota-node iri[20948]:         at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
Feb 26 11:05:40 iota-node iri[20948]:         at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
Feb 26 11:05:40 iota-node iri[20948]:         at java.nio.file.Files.newOutputStream(Files.java:216)
Feb 26 11:05:40 iota-node iri[20948]:         at java.nio.file.Files.copy(Files.java:3016)
Feb 26 11:05:40 iota-node iri[20948]:         at org.iota.ict.ixi.IxiModuleHolder.install(IxiModuleHolder.java:95)
Feb 26 11:05:40 iota-node iri[20948]:         at org.iota.ict.api.JsonIct.addModule(JsonIct.java:185)
Feb 26 11:05:40 iota-node iri[20948]:         ... 22 more```
