### ISSUE TITLE
Disabling GUI makes some IXI stop working 

### ISSUE THREAD

**Issue by lambtho12** [iotaledger/ict#34]
### Bug description
Some IXIs rely on rest_api, which is itself disabled if GUI is disabled in ìct.cfg`. It would be better to have more control in order to let rest_api open, while GUI is disabled.

### Ict version
Ict 0.5

### Hardware Spec
Raspberry Pi 3b+ , diepti

### Steps To Reproduce
1. Disable GUI
2. Try to use report.ixi

### Expected behaviour
IXIs should work even without web interface
-> Solution : two parameters : `rest_api_enabled` and `gui_enabled` for serving interface.

### Actual behaviour
IXIs stop working due to lack of rest_api access when GUI is disabled.

### Errors
N/A

**Comment by mikrohash** [comment]
> Solution : two parameters : `rest_api_enabled` and `gui_enabled` for serving interface.

What use is there in disabling the GUI while keeping the API alive?

**Comment by lambtho12** [comment]
People may want to not use GUI and make it not accessible, while still use IXIs that require API access. For instance, I do not care for a GUI on all my Icts, I just need it on one of my Icts to discusses on Chat.ixi . So I could disable the GUI on all the others. But doing so will also make report.ixi stop working on these.

**Comment by mikrohash** [comment]
> People may want to not use GUI and make it not accessible, while still use IXIs that require API access.

What would be the advantage of making it not accessible over just not using it? As soon as you expose your API, anybody could connect a GUI to it.
