### ISSUE TITLE
SSL [feature-request]

### ISSUE THREAD

**Issue by a223y** [iotaledger/ict#40]
SSL on web-gui and rest api by default would hurt nobody, maybe even better, it could safe somebody's password from being stolen.

**Comment by mikrohash** [comment]
Is there any way to do this without requiring the user to manually import the certificate into their browser?

**Comment by mikrohash** [comment]
Otherwise I would add this as an opt-in configuration option since we cannot expect the average user to go through this manually.

**Comment by a223y** [comment]
Let's encrypt certificates work seamlessly for user, there you must just auto-renew them via cron, cert-bot installation is in copy paste installation of iri node at iota partners. I suggest leaving a certificates(cert.pem, privkey.pem) path possibility in config along with "ssl_enabled" option and once that's done I can publish on Medium, how to set it up and I guess somebody will even write bash for that. All you need for that is some fully qualified domain name.

**Comment by ixuz** [comment]
I don't a need to import a certificate into the browser's trust store, instead the Ict operator can simply acquire a trusted certificate via traditional means from an established CA.
Would be neat to if the trusted certificate could be imported to Ict directly via the WebGUI.
I agree that usage of TLS should be opt-in.

**Comment by mikrohash** [comment]
> Would be neat to if the trusted certificate could be imported to Ict directly via the WebGUI.
I agree that usage of TLS should be opt-in.

Agree, this should be feasible. Integrating Let's Encrypt directly into Ict with maintenance is too much overhead. Could be done with an letsencrypt.ixi though once the opt-in is implemented. 😉

**Comment by no8ody** [comment]
To use https for the GUI is not difficult with nginx over a proxy, but then chat.ixi does not work, since there https + port 2019 is taken (at least I just do not know how to do it).

**Comment by mikrohash** [comment]
Spark already offers a one-line solution to add SSL to the original port. No need to use a second port or additional proxy software.
