### ISSUE TITLE
WebGUI fails to show Ict configuration panels

### ISSUE THREAD

**Issue by ixuz** [iotaledger/ict#62]
The Ict configuration panels show up with no content after initial login.
It does not matter how long the browser waits for the content to load.

![19-03-27 10-30-00](https://user-images.githubusercontent.com/7243912/55066063-43321300-507d-11e9-8f9e-9bcf5d7daa75.png)

**Workaround 1:**
Navigate to another view, e.g. Home/Log.
Wait for a bit before navigating back to Configuration-view.
_No manual page refresh required._

**Workaround 2:**
Do a manual page refresh.

**Expected behaviour:**
The Configuration page should populate the panels, even if it takes a couple of seconds to load.

**Comment by mikrohash** [comment]
@ixuz or @rihardsgravis, can this be closed?

**Comment by ixuz** [comment]
This issue seem to be resolved after deploying Ict `0.7-SNAPSHOT` to all my nodes. :+1:

**Comment by rihardsgravis** [comment]
I could not reproduce this bug anymore. I think that this can be closed if there are no new reports.
