### ISSUE TITLE
Unexpected behavior: onReceive called 2 times when listening Environments.GOSSIP_PREPROCESSOR_CHAIN

### ISSUE THREAD

**Issue by ben-75** [iotaledger/ict#68]
When adding a single EffectListener on environment GOSSIP_PREPROCESSOR_CHAIN, it appears that submitting one single transaction will trigger the "onReceive" method twice.

Both invocations receive a different ChainedEffectListener.Output instance.
But those 2 instances reference the same GossipEvent instance.

It don't seems to be the expected behavior.

**Comment by mikrohash** [comment]
Fixed by using a `GossipPreprocessor` instance instead of `EffectListener<ChainedEffectListener.Output>`
