### ISSUE TITLE
Can't start ict with too many neighbors

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/ict#70]
`ERROR [main/Main]   Could not start Ict. - java.lang.
IllegalStateException: Already reached maximum amount of neighbors.`

The neighbours were added by ictinder and I had to delete them manually in ict.cfg so I could start ict again.
If there are too many neighbors you should get an error in the log that there are too many neighbors but ict should start anyway with the first three neighbors in the list

**Comment by mikrohash** [comment]
> If there are too many neighbors you should get an error in the log that there are too many neighbors but ict should start anyway with the first three neighbors in the list

I prefer it to not start as a way of making the user aware that there is an issue. Now that we know that we can investigate why there were so many neighbors in the first place.
