### ISSUE TITLE
Compilation Fails because of Log4j Dependency

### ISSUE THREAD

**Issue by mikrohash** [iotaledger/ict#75]
Thibault reported this error when trying to compile Ict from source:

```
> Task :compileJava FAILED
warning: [options] bootstrap class path not set in conjunction with -source 1.7
~/iota/ict/src/main/java/org/iota/ict/api/RouteImpl.java:3: error: package org.apache.logging.log4j.core does not exist
import org.apache.logging.log4j.core.LogEvent;
                                    ^
~/iota/ict/src/main/java/org/iota/ict/utils/LogAppender.java:3: error: package org.apache.logging.log4j.core does not exist
import org.apache.logging.log4j.core.*;
```

We could trace it back to this commit: https://github.com/iotaledger/ict/commit/da2ba74244da6111bf5e8034736bf334ee74b914. Using the old version worked as intended. 
@ben-75 could you look into it?

**Comment by ben-75** [comment]
Caused by gradle 5.4.1 (latest) including maven transitive dependencies differently. ( https://docs.gradle.org/5.0/release-notes.html#potential-breaking-changes)
